version: 2.1

restore_cache: &restore_cache
  restore_cache:
    key: dependency-cache-{{ checksum "package-lock.json" }}

manage_dependencies: &manage_dependencies
  run:
    name: Install/Manage dependencies
    command: npm ci && npx lerna bootstrap

build: &build
  run:
    name: Build/Compile project
    command: npm run build

unit_tests: &unit_tests
  run:
    name: Run unit tests.
    command: npm run test:coverage -- --runInBand --silent --ci

tests: &tests
  steps:
    - checkout
    - <<: *restore_cache
    - <<: *manage_dependencies
    - <<: *build
    - <<: *unit_tests

who_am_i: &who_am_i
  run:
    name: Tell the CI who I am
    command: |
      git config --global user.email $GIT_EMAIL
      git config --global user.name $GIT_USERNAME

jobs:
  #region PREPARATION
  dependency_cache:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - <<: *restore_cache
      - run: npm ci --prefer-offline && npx lerna bootstrap
      - save_cache: # I hope they supprot globbing/wildcard pattern :cry:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
  analysis:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *manage_dependencies
      - run:
          name: Run linting.
          command: npm run lint
      - run:
          name: Run Security Check.
          command: npx lerna exec --no-bail -- npm audit --quiet --audit-level high
      - run:
          name: Found security issue! Check if it's fixable or just have low severity.
          command: npx lerna exec --no-bail -- npm audit fix --quiet
          when: on_fail
      - run:
          name: Validate commit messages
          command: npx commitlint --from=${CIRCLE_BRANCH} --to=${CIRCLE_SHA1}
          when: always
  #endregion

  #region CROSS-BUILD
  node-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *manage_dependencies
      - <<: *build
      - <<: *unit_tests
      - run:
          name: Submit coverage data to codecov.
          command: |
            if [[ -z $CIRCLE_PULL_REQUEST ]]; then
              bash <(curl -s https://codecov.io/bash)
            fi
          when: on_success
  node10-latest:
    docker:
      - image: circleci/node:10
    <<: *tests
  node8-latest:
    docker:
      - image: circleci/node:8
    <<: *tests
  #endregion

  #region RELEASE VERSION
  deploy-docs:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *manage_dependencies
      - run:
          name: Generate documentations
          command: npm run predocs
      - <<: *who_am_i
      - run:
          name: Push the documentations to Github pages
          command: npx gh-pages --dist docs
  draft:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *manage_dependencies
      - run:
          name: Validate Commit Messages
          command: npx commitlint --from=$(git describe --tags --abbrev=0) --to=$(git rev-parse HEAD)
      - run: npm run build && npx lerna exec --no-bail -- npm pack
      - run: npm run predocs && tar cvzf docs-$CIRCLE_TAG.tgz docs
      - <<: *who_am_i
      - run:
          name: Draft Github release
          command: | # TODO: change to lerna (MAYBE)
            sudo su -c 'sudo npm i -g DrSensor/gh-release'
            GH_RELEASE_GITHUB_API_TOKEN=$GH_TOKEN gh-release --draft --assets $(ls -m packages/*/*.tgz | tr -d ' ') --yes
  publish:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: set npm TOKEN
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - <<: *restore_cache
      - <<: *manage_dependencies
      - run: npx lerna publish from-git --no-git-reset --yes
  #endregion

workflows:
  version: 2
  build and publish on tagging:
    jobs:
      #region PREPARATION
      - dependency_cache:
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /.*/
      - analysis:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      #endregion

      #region CROSS-BUILD
      - node-latest:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      - node8-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
      - node10-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
      #endregion


      #region RELEASE VERSION
      - draft:
          requires:
            - node-latest
            - analysis
          filters:
            tags:
              only: /^v\d+[.]\d+[.]\d+(-\d+|-\w+|)$/
            branches:
              ignore: /.*/
      - deploy-docs:
          requires:
            - publish package?
          filters:
            tags:
              only: /^v\d+[.]\d+[.]\d+$/ # don't support pre-release
            branches:
              ignore: /.*/
      - publish package?:
          type: approval
          requires:
            - draft
          filters:
            tags:
              only: /^v\d+[.]\d+[.]\d+(-\d+|-\w+|)$/
      - publish:
          requires:
            - publish package?
          filters:
            tags:
              only: /^v\d+[.]\d+[.]\d+(-\d+|-\w+|)$/
      #endregion
